config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users

  root to: 'recipe#index', as: :user_recipes_root

  get 'users/:user_id/foods', to: 'food#index', as: 'user_foods'
  get 'users/:user_id/foods/new', to: 'food#new', as: 'new_user_food'
  post 'users/:user_id/foods', to: 'food#create', as: 'create_user_food'
  delete 'users/:user_id/foods/:id', to: 'food#destroy', as: 'destroy_user_food'

  get 'users/:user_id/recipes', to: 'recipe#index', as: 'user_recipes'
  get 'users/:user_id/recipes/new', to: 'recipe#new', as: 'new_user_recipe'
  post 'users/:user_id/recipes', to: 'recipe#create', as: 'create_user_recipe'
  get 'users/:user_id/recipes/:id', to: 'recipe#show', as: 'show_user_recipe'
  delete 'users/:user_id/recipes/:id', to: 'recipe#destroy', as: 'destroy_user_recipe'

  get 'users/:user_id/recipes/:recipe_id/recipe_foods/new', to: 'recipe_foods#new', as: 'new_user_recipe_recipe_food'
  get 'users/:user_id/recipes/:recipe_id/recipe_foods', to: 'recipe_foods#index', as: 'user_recipe_recipe_foods'
  post 'users/:user_id/recipes/:recipe_id/recipe_foods', to: 'recipe_foods#create', as: 'create_user_recipe_recipe_food'
  delete 'users/:user_id/recipes/:recipe_id/recipe_foods/:id', to: 'recipe_foods#destroy', as: 'destroy_user_recipe_recipe_food'
  get 'users/:user_id/recipes/:recipe_id/recipe_foods/:id/edit', to: 'recipe_foods#edit', as: 'edit_user_recipe_recipe_food'
  patch 'users/:user_id/recipes/:recipe_id/recipe_foods/:id/update', to: 'recipe_foods#update', as: 'update_user_recipe_recipe_food'


  patch 'users/:user_id/recipes/:id/toggle_public', to: 'recipe#toggle_public', as: 'toggle_public_recipe'

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'

  get '/general_shopping_list', to: 'shopping_lists#index', as: 'general_shopping_list'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @recipes = @user.recipes
  end

  def show
    @user = User.find(current_user.id)
    @recipe = @user.recipes.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @foods = Food.all
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])

    # Toggle the 'public' attribute
    @recipe.update(public: !@recipe.public)

    respond_to(&:js)
  end

  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html { render :new, locals: { user: current_user, recipe: @recipe } }
    end
  end

  def create
    @user = User.find(current_user.id)
    @recipe = @user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to new_user_recipe_path(@user), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @recipe = @user.recipes.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to user_recipes_path(@user), notice: 'Recipe was successfully deleted.' }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipe/index.html.erb
<div class="recipes-container">
<h2 class="main-title">Recipe List</h2>
  <% if !@recipes.empty? %>
    <% @recipes.each do |recipe| %>
      <div>
        <div>
          <div>
            <h3 class="recipe-name">
              <%= link_to recipe.name, show_user_recipe_path(current_user, id: recipe.id) %>
            </h3>
            <% if can? :destroy, recipe %>
            <%= link_to "Delete", destroy_user_recipe_path(user_id: current_user, id: recipe.id), method: :delete %>
            <% end %>
          </div>
          <div>
            <div>
              <p><%= recipe.description%></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No recipes yet</p>
  <% end %>

  <% if can? :create, Recipe %>
  <div>
    <%= link_to "Add Recipe", new_user_recipe_path(current_user) %>
  <% end %>
</div>