config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users

  root to: 'recipe#index', as: :user_recipes_root

  get 'users/:user_id/foods', to: 'food#index', as: 'user_foods'
  get 'users/:user_id/foods/new', to: 'food#new', as: 'new_user_food'
  post 'users/:user_id/foods', to: 'food#create', as: 'create_user_food'
  delete 'users/:user_id/foods/:id', to: 'food#destroy', as: 'destroy_user_food'

  get 'users/:user_id/recipes', to: 'recipe#index', as: 'user_recipes'
  get 'users/:user_id/recipes/new', to: 'recipe#new', as: 'new_user_recipe'
  post 'users/:user_id/recipes', to: 'recipe#create', as: 'create_user_recipe'
  get 'users/:user_id/recipes/:id', to: 'recipe#show', as: 'show_user_recipe'
  delete 'users/:user_id/recipes/:id', to: 'recipe#destroy', as: 'destroy_user_recipe'

  get 'users/:user_id/recipes/:recipe_id/recipe_foods/new', to: 'recipe_foods#new', as: 'new_user_recipe_recipe_food'
  get 'users/:user_id/recipes/:recipe_id/recipe_foods', to: 'recipe_foods#index', as: 'user_recipe_recipe_foods'
  post 'users/:user_id/recipes/:recipe_id/recipe_foods', to: 'recipe_foods#create', as: 'create_user_recipe_recipe_food'
  delete 'users/:user_id/recipes/:recipe_id/recipe_foods/:id', to: 'recipe_foods#destroy', as: 'destroy_user_recipe_recipe_food'
  get 'users/:user_id/recipes/:recipe_id/recipe_foods/:id/edit', to: 'recipe_foods#edit', as: 'edit_user_recipe_recipe_food'
  patch 'users/:user_id/recipes/:recipe_id/recipe_foods/:id/update', to: 'recipe_foods#update', as: 'update_user_recipe_recipe_food'


  patch 'users/:user_id/recipes/:id/toggle_public', to: 'recipe#toggle_public', as: 'toggle_public_recipe'

  get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'

  get '/general_shopping_list', to: 'shopping_lists#index', as: 'general_shopping_list'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_include_tag "rails-ujs" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">RECIPE APP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Recipes", user_recipes_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Food", user_foods_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Shopping List", general_shopping_list_path(current_user), class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
       
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<% if flash[:success] %>
  <div class="alert alert-success w-50 m-auto">
    <%= flash[:success] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger w-50 m-auto">
    <%= flash[:error] %>
  </div>
<% end %>
<% if notice %>
  <p class="notice w-50">
     <div class="alert alert-warning w-50 m-auto">
    <%= notice %>
  </div>
  </p>
<% end %>
<% if alert %>
  <p class="alert w-50">
    <div class="alert alert-danger w-50 m-auto">
      <%= alert %>
    </div>
  </p>
<% end %>
    <%= yield %>
  </body>
</html>